defining types to fix compilation errors with musl
musl compiler (as used in openwrt "designated driver") fails compiling
due to missing unsigned types.

src/ds2438.c:29:4: error: unknown type name 'ushort'
ushort lastcrc8=255;